project:
  type: website
  output-dir: docs
  execute-dir: project
  render: 
  - index.qmd
  - Depression_Website.qmd

website:
  title: "M244 Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Depression_Website.qmd
        text: Final Report

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


execute:
  echo: false
  warning: false
  message: false



